name: Daily Algorithm Publish

on:
  schedule:
    # KST 00:00 == UTC 15:00
    - cron: "0 15 * * *"
  workflow_dispatch: {}

jobs:
  publish-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git identity (noreply)
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Pick next pending file
        id: pick
        shell: bash
        run: |
          NEXT_FILE=$(ls pending/*.py 2>/dev/null | sort | head -n 1 || true)
          if [ -z "$NEXT_FILE" ]; then
            echo "found=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          BASENAME=$(basename "$NEXT_FILE")   # ex: 1543.py
          NUM="${BASENAME%%.*}"               # ex: 1543
          DEST_DIR="algorithms"
          mkdir -p "$DEST_DIR"
          DEST_PATH="$DEST_DIR/$BASENAME"

          echo "NEXT_FILE=$NEXT_FILE"   >> "$GITHUB_OUTPUT"
          echo "DEST_PATH=$DEST_PATH"   >> "$GITHUB_OUTPUT"
          echo "NUM=$NUM"               >> "$GITHUB_OUTPUT"
          echo "found=true"             >> "$GITHUB_OUTPUT"

      - name: Move, commit, push
        if: steps.pick.outputs.found == 'true'
        run: |
          git mv "${{ steps.pick.outputs.NEXT_FILE }}" "${{ steps.pick.outputs.DEST_PATH }}"
          git add "${{ steps.pick.outputs.DEST_PATH }}"
          git commit -m "feat(algo): publish #${{ steps.pick.outputs.NUM }}"
          git push
